/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: 'var(--color-ink)',
        paper: 'var(--color-paper)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        muted: 'var(--color-muted)',
        dim: 'var(--color-dim)',
        subtle: 'var(--color-subtle)',
        border: 'var(--color-border)',
        'border-bright': 'var(--color-border-bright)',
        'border-focus': 'var(--color-border-focus)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-dim': 'var(--color-accent-dim)',
        cyan: 'var(--color-cyan)',
        'cyan-dim': 'var(--color-cyan-dim)',
        success: 'var(--color-success)',
        'success-dim': 'var(--color-success-dim)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--text-xs)', { lineHeight: 'var(--leading-tight)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--leading-base)' }],
        base: ['var(--text-base)', { lineHeight: 'var(--leading-base)' }],
        lg: ['var(--text-lg)', { lineHeight: 'var(--leading-base)' }],
        xl: ['var(--text-xl)', { lineHeight: 'var(--leading-tight)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-tight)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)' }],
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        base: 'var(--leading-base)',
        loose: 'var(--leading-loose)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        accent: 'var(--shadow-accent)',
        cyan: 'var(--shadow-cyan)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--ease-default)',
        snap: 'var(--ease-snap)',
      },
      animation: {
        'beacon-pulse': 'beaconPulse 2.2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'beacon-alert': 'beaconPulse 1.1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'border-beam': 'border-beam var(--duration) infinite linear',
        'glitch-flicker': 'glitch-flicker 7s ease-in-out infinite',
        'marquee-x': 'marquee-x 30s linear infinite',
      },
      keyframes: {
        beaconPulse: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.35', transform: 'scale(0.8)' },
        },
        'border-beam': {
          '100%': { 'offset-distance': '100%' },
        },
        'glitch-flicker': {
          '0%, 94%, 100%': { opacity: '1', transform: 'none' },
          '95%': { opacity: '0.8', transform: 'translateX(2px) skewX(-2deg)' },
          '96%': { opacity: '1', transform: 'none' },
          '97%': { opacity: '0.85', transform: 'translateX(-1px)' },
          '98%': { opacity: '1', transform: 'none' },
        },
        'marquee-x': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
      },
      zIndex: {
        'scanline': '9999',
        'modal': '100',
        'toast': '200',
        'dropdown': '50',
      },
    },
  },
  plugins: [],
};