apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xploitverse-client
  namespace: xploitverse
  labels:
    app.kubernetes.io/name: xploitverse-client
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xploitverse-client
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
