apiVersion: v1
kind: ServiceAccount
metadata:
  name: xploitverse-backend
  namespace: xploitverse
  labels:
    app.kubernetes.io/name: xploitverse-backend
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
